// Tests for the route exports (Routes, Itineraries and the weekly schedule). The made-up files in packages/fixtures were read with the old Python
// importer and the numbers and sample rows below are what it answered. The inline scenarios were
// built in a temporary folder, run through the old importer too, and its answers copied in.

import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { vi } from 'vitest';
import { dispatchTimes, sharedRows, totalMismatch } from '../models/routes';
import { importRouteExport, RouteDataImportError } from './routedata';
import { fixturePath, runScenario, withScenarioFile, type Sample, type Scenario } from './testkit';

const FIXTURES: Array<{
  folder: string;
  file: string;
  kind: string;
  count: number;
  day: string | null;
  shared: number;
  durations: number;
  times: Array<[string, number]>;
  sample: Sample;
}> = [
  {
    folder: 'itineraries',
    file: 'Itineraries_XXX1_2026-10-03_21_36 (CDT).xlsx',
    kind: 'itineraries',
    count: 25,
    day: '2026-10-03',
    shared: 0,
    durations: 0,
    times: [
      ['10:20am', 12],
      ['10:25am', 11],
      ['2:30pm', 2],
    ],
    sample: [
      [
        0,
        {
          transporterId: 'A1QVVPYVZD6R9F',
          driverName: 'Beatrice Sutherland',
          routeCode: 'CX180',
          dispatchTime: '10:25am',
          serviceType: 'Standard Parcel Electric - Rivian MEDIUM',
          routeDuration: '',
          vin: '7FCYRFJ30PN317983',
          detail: '10:34am',
          sharedDrivers: 'Beatrice Sutherland',
          sharedIds: 'A1QVVPYVZD6R9F',
          pad: '',
        },
      ],
      [
        12,
        {
          transporterId: 'A63AK2RYZDOMF0',
          driverName: 'Greta Eastwood',
          routeCode: 'CX181',
          dispatchTime: '10:20am',
          serviceType: 'Standard Parcel Electric - Rivian MEDIUM',
          routeDuration: '',
          vin: '7FCYZAP63PN575306',
          detail: '10:23am',
          sharedDrivers: 'Greta Eastwood',
          sharedIds: 'A63AK2RYZDOMF0',
          pad: '',
        },
      ],
      [
        24,
        {
          transporterId: 'A1I13S2WRY55FH',
          driverName: 'Ariana Nethercott',
          routeCode: 'CX188',
          dispatchTime: '10:20am',
          serviceType: 'Standard Parcel Electric - Rivian MEDIUM',
          routeDuration: '',
          vin: '7FCBMBV93PN085598',
          detail: '9:56am',
          sharedDrivers: 'Ariana Nethercott',
          sharedIds: 'A1I13S2WRY55FH',
          pad: '',
        },
      ],
    ],
  },
  {
    folder: 'routes',
    file: 'Routes_XXX1_2026-09-01_12_20 (CDT).xlsx',
    kind: 'routes',
    count: 29,
    day: '2026-09-01',
    shared: 10,
    durations: 0,
    times: [
      ['10:20am', 16],
      ['10:25am', 12],
      ['2:30pm', 1],
    ],
    sample: [
      [
        0,
        {
          transporterId: 'A486QRCQCVMTG1',
          driverName: 'Nadine Abernathy',
          routeCode: 'CX16',
          dispatchTime: '10:20am',
          serviceType: 'Standard Parcel Electric - Rivian MEDIUM',
          routeDuration: '',
          vin: '',
          detail: 'AT_RISK',
          sharedDrivers: 'Nadine Abernathy',
          sharedIds: 'A486QRCQCVMTG1',
          pad: '',
        },
      ],
      [
        14,
        {
          transporterId: 'A3FM1CRWW54MMO',
          driverName: 'Yara Halloran',
          routeCode: 'CX13',
          dispatchTime: '10:20am',
          serviceType: 'Standard Parcel Electric - Rivian MEDIUM',
          routeDuration: '',
          vin: '',
          detail: 'COMPLETE',
          sharedDrivers: 'Yara Halloran',
          sharedIds: 'A3FM1CRWW54MMO',
          pad: '',
        },
      ],
      [
        28,
        {
          transporterId: 'A5QUM4XU1H9HQS',
          driverName: 'Mabel Kensington',
          routeCode: 'CX29',
          dispatchTime: '10:25am',
          serviceType: 'Standard Parcel Electric - Rivian MEDIUM',
          routeDuration: '',
          vin: '',
          detail: 'COMPLETE',
          sharedDrivers: 'Mabel Kensington',
          sharedIds: 'A5QUM4XU1H9HQS',
          pad: '',
        },
      ],
    ],
  },
  {
    folder: 'routes',
    file: 'Routes_XXX1_2026-09-25_09_54 (CDT).xlsx',
    kind: 'routes',
    count: 25,
    day: '2026-09-25',
    shared: 0,
    durations: 0,
    times: [
      ['10:20am', 12],
      ['10:25am', 13],
    ],
    sample: [
      [
        0,
        {
          transporterId: 'A0DZDWECHDJ5TO',
          driverName: 'Paloma Marcus Selwyn',
          routeCode: 'CX171',
          dispatchTime: '10:25am',
          serviceType: 'Standard Parcel Electric - Rivian MEDIUM',
          routeDuration: '',
          vin: '',
          detail: 'ON_TIME',
          sharedDrivers: 'Paloma Marcus Selwyn',
          sharedIds: 'A0DZDWECHDJ5TO',
          pad: '',
        },
      ],
      [
        12,
        {
          transporterId: 'A9CW8HB7Y0K8F4',
          driverName: 'Darcy Gresham',
          routeCode: 'CX188',
          dispatchTime: '10:25am',
          serviceType: 'Standard Parcel Electric - Rivian MEDIUM',
          routeDuration: '',
          vin: '',
          detail: 'ON_TIME',
          sharedDrivers: 'Darcy Gresham',
          sharedIds: 'A9CW8HB7Y0K8F4',
          pad: '',
        },
      ],
      [
        24,
        {
          transporterId: 'A9LE0ZXWQH9RYQ',
          driverName: 'Sabrina Gresham',
          routeCode: 'CX182',
          dispatchTime: '10:20am',
          serviceType: 'Standard Parcel Electric - Rivian MEDIUM',
          routeDuration: '',
          vin: '',
          detail: 'ON_TIME',
          sharedDrivers: 'Sabrina Gresham',
          sharedIds: 'A9LE0ZXWQH9RYQ',
          pad: '',
        },
      ],
    ],
  },
];

const SCHEDULE_FIXTURES: Array<{
  file: string;
  day: string;
  count: number;
  total: number | null;
  mismatch: number | null;
  times: Array<[string, number]>;
  shared: number;
  sample: Sample;
}> = [
  {
    file: 'Week-36-Schedule.xlsx',
    day: '2026-08-31',
    count: 12,
    total: 12,
    mismatch: null,
    times: [
      ['9:55am', 2],
      ['10:20am', 5],
      ['10:25am', 3],
      ['2:30pm', 2],
    ],
    shared: 2,
    sample: [
      [
        0,
        {
          transporterId: 'AK92X3BJNUBTF',
          driverName: 'Carmen Abernathy',
          routeCode: '',
          dispatchTime: '9:55am',
          serviceType: 'Standard Parcel Step Van - US',
          routeDuration: '',
          vin: '',
          detail: '10 hrs',
          sharedDrivers: 'Carmen Abernathy',
          sharedIds: 'AK92X3BJNUBTF',
          pad: '',
        },
      ],
      [
        6,
        {
          transporterId: 'A6URN0K4YHEUUX',
          driverName: 'Elodie Hadley Hargrove',
          routeCode: '',
          dispatchTime: '10:25am',
          serviceType: 'Standard Parcel Electric - Rivian MEDIUM',
          routeDuration: '',
          vin: '',
          detail: '10 hrs',
          sharedDrivers: 'Elodie Hadley Hargrove',
          sharedIds: 'A6URN0K4YHEUUX',
          pad: '',
        },
      ],
      [
        11,
        {
          transporterId: 'A9ZG8P8IMK2LUL',
          driverName: 'Caleb Eldridge',
          routeCode: '',
          dispatchTime: '2:30pm',
          serviceType: 'Standard Parcel - Large Van - Recycle',
          routeDuration: '',
          vin: '',
          detail: '8 hrs',
          sharedDrivers: 'Caleb Eldridge|Caleb Wadsworth',
          sharedIds: 'A9ZG8P8IMK2LUL|A34KITC8D730CW',
          pad: '',
        },
      ],
    ],
  },
  {
    file: 'Week-36-Schedule.xlsx',
    day: '2026-09-01',
    count: 11,
    total: 12,
    mismatch: 12,
    times: [
      ['9:55am', 2],
      ['10:20am', 4],
      ['10:25am', 3],
      ['2:30pm', 2],
    ],
    shared: 2,
    sample: [
      [
        0,
        {
          transporterId: 'AK92X3BJNUBTF',
          driverName: 'Carmen Abernathy',
          routeCode: '',
          dispatchTime: '9:55am',
          serviceType: 'Standard Parcel Step Van - US',
          routeDuration: '',
          vin: '',
          detail: '10 hrs',
          sharedDrivers: 'Carmen Abernathy',
          sharedIds: 'AK92X3BJNUBTF',
          pad: '',
        },
      ],
      [
        5,
        {
          transporterId: 'ANC8ZRCZP4NFS',
          driverName: 'Nell Bellamy',
          routeCode: '',
          dispatchTime: '10:25am',
          serviceType: 'Standard Parcel Electric - Rivian MEDIUM',
          routeDuration: '',
          vin: '',
          detail: '10 hrs',
          sharedDrivers: 'Nell Bellamy',
          sharedIds: 'ANC8ZRCZP4NFS',
          pad: '',
        },
      ],
      [
        10,
        {
          transporterId: 'A9ZG8P8IMK2LUL',
          driverName: 'Caleb Eldridge',
          routeCode: '',
          dispatchTime: '2:30pm',
          serviceType: 'Standard Parcel - Large Van - Recycle',
          routeDuration: '',
          vin: '',
          detail: '8 hrs',
          sharedDrivers: 'Caleb Eldridge|Caleb Wadsworth',
          sharedIds: 'A9ZG8P8IMK2LUL|A34KITC8D730CW',
          pad: '',
        },
      ],
    ],
  },
  {
    file: 'Week-36-Schedule.xlsx',
    day: '2026-09-02',
    count: 12,
    total: 12,
    mismatch: null,
    times: [
      ['9:55am', 2],
      ['10:20am', 5],
      ['10:25am', 3],
      ['2:30pm', 2],
    ],
    shared: 2,
    sample: [
      [
        0,
        {
          transporterId: 'AK92X3BJNUBTF',
          driverName: 'Carmen Abernathy',
          routeCode: '',
          dispatchTime: '9:55am',
          serviceType: 'Standard Parcel Step Van - US',
          routeDuration: '',
          vin: '',
          detail: '10 hrs',
          sharedDrivers: 'Carmen Abernathy',
          sharedIds: 'AK92X3BJNUBTF',
          pad: '',
        },
      ],
      [
        6,
        {
          transporterId: 'A6URN0K4YHEUUX',
          driverName: 'Elodie Hadley Hargrove',
          routeCode: '',
          dispatchTime: '10:25am',
          serviceType: 'Standard Parcel Electric - Rivian MEDIUM',
          routeDuration: '',
          vin: '',
          detail: '10 hrs',
          sharedDrivers: 'Elodie Hadley Hargrove',
          sharedIds: 'A6URN0K4YHEUUX',
          pad: '',
        },
      ],
      [
        11,
        {
          transporterId: 'A9ZG8P8IMK2LUL',
          driverName: 'Caleb Eldridge',
          routeCode: '',
          dispatchTime: '2:30pm',
          serviceType: 'Standard Parcel - Large Van - Recycle',
          routeDuration: '',
          vin: '',
          detail: '8 hrs',
          sharedDrivers: 'Caleb Eldridge|Caleb Wadsworth',
          sharedIds: 'A9ZG8P8IMK2LUL|A34KITC8D730CW',
          pad: '',
        },
      ],
    ],
  },
  {
    file: 'Week-36-Schedule.xlsx',
    day: '2026-09-03',
    count: 12,
    total: 12,
    mismatch: null,
    times: [
      ['9:55am', 2],
      ['10:20am', 5],
      ['10:25am', 3],
      ['2:30pm', 2],
    ],
    shared: 2,
    sample: [
      [
        0,
        {
          transporterId: 'AK92X3BJNUBTF',
          driverName: 'Carmen Abernathy',
          routeCode: '',
          dispatchTime: '9:55am',
          serviceType: 'Standard Parcel Step Van - US',
          routeDuration: '',
          vin: '',
          detail: '10 hrs',
          sharedDrivers: 'Carmen Abernathy',
          sharedIds: 'AK92X3BJNUBTF',
          pad: '',
        },
      ],
      [
        6,
        {
          transporterId: 'A6URN0K4YHEUUX',
          driverName: 'Elodie Hadley Hargrove',
          routeCode: '',
          dispatchTime: '10:25am',
          serviceType: 'Standard Parcel Electric - Rivian MEDIUM',
          routeDuration: '',
          vin: '',
          detail: '10 hrs',
          sharedDrivers: 'Elodie Hadley Hargrove',
          sharedIds: 'A6URN0K4YHEUUX',
          pad: '',
        },
      ],
      [
        11,
        {
          transporterId: 'A9ZG8P8IMK2LUL',
          driverName: 'Caleb Eldridge',
          routeCode: '',
          dispatchTime: '2:30pm',
          serviceType: 'Standard Parcel - Large Van - Recycle',
          routeDuration: '',
          vin: '',
          detail: '8 hrs',
          sharedDrivers: 'Caleb Eldridge|Caleb Wadsworth',
          sharedIds: 'A9ZG8P8IMK2LUL|A34KITC8D730CW',
          pad: '',
        },
      ],
    ],
  },
  {
    file: 'Week-36-Schedule.xlsx',
    day: '2026-09-04',
    count: 12,
    total: 12,
    mismatch: null,
    times: [
      ['9:55am', 2],
      ['10:20am', 5],
      ['10:25am', 3],
      ['2:30pm', 2],
    ],
    shared: 2,
    sample: [
      [
        0,
        {
          transporterId: 'AK92X3BJNUBTF',
          driverName: 'Carmen Abernathy',
          routeCode: '',
          dispatchTime: '9:55am',
          serviceType: 'Standard Parcel Step Van - US',
          routeDuration: '',
          vin: '',
          detail: '10 hrs',
          sharedDrivers: 'Carmen Abernathy',
          sharedIds: 'AK92X3BJNUBTF',
          pad: '',
        },
      ],
      [
        6,
        {
          transporterId: 'A6URN0K4YHEUUX',
          driverName: 'Elodie Hadley Hargrove',
          routeCode: '',
          dispatchTime: '10:25am',
          serviceType: 'Standard Parcel Electric - Rivian MEDIUM',
          routeDuration: '',
          vin: '',
          detail: '10 hrs',
          sharedDrivers: 'Elodie Hadley Hargrove',
          sharedIds: 'A6URN0K4YHEUUX',
          pad: '',
        },
      ],
      [
        11,
        {
          transporterId: 'A9ZG8P8IMK2LUL',
          driverName: 'Caleb Eldridge',
          routeCode: '',
          dispatchTime: '2:30pm',
          serviceType: 'Standard Parcel - Large Van - Recycle',
          routeDuration: '',
          vin: '',
          detail: '8 hrs',
          sharedDrivers: 'Caleb Eldridge|Caleb Wadsworth',
          sharedIds: 'A9ZG8P8IMK2LUL|A34KITC8D730CW',
          pad: '',
        },
      ],
    ],
  },
  {
    file: 'Week-36-Schedule.xlsx',
    day: '2026-09-05',
    count: 12,
    total: 12,
    mismatch: null,
    times: [
      ['9:55am', 2],
      ['10:20am', 5],
      ['10:25am', 3],
      ['2:30pm', 2],
    ],
    shared: 2,
    sample: [
      [
        0,
        {
          transporterId: 'AK92X3BJNUBTF',
          driverName: 'Carmen Abernathy',
          routeCode: '',
          dispatchTime: '9:55am',
          serviceType: 'Standard Parcel Step Van - US',
          routeDuration: '',
          vin: '',
          detail: '10 hrs',
          sharedDrivers: 'Carmen Abernathy',
          sharedIds: 'AK92X3BJNUBTF',
          pad: '',
        },
      ],
      [
        6,
        {
          transporterId: 'A6URN0K4YHEUUX',
          driverName: 'Elodie Hadley Hargrove',
          routeCode: '',
          dispatchTime: '10:25am',
          serviceType: 'Standard Parcel Electric - Rivian MEDIUM',
          routeDuration: '',
          vin: '',
          detail: '10 hrs',
          sharedDrivers: 'Elodie Hadley Hargrove',
          sharedIds: 'A6URN0K4YHEUUX',
          pad: '',
        },
      ],
      [
        11,
        {
          transporterId: 'A9ZG8P8IMK2LUL',
          driverName: 'Caleb Eldridge',
          routeCode: '',
          dispatchTime: '2:30pm',
          serviceType: 'Standard Parcel - Large Van - Recycle',
          routeDuration: '',
          vin: '',
          detail: '8 hrs',
          sharedDrivers: 'Caleb Eldridge|Caleb Wadsworth',
          sharedIds: 'A9ZG8P8IMK2LUL|A34KITC8D730CW',
          pad: '',
        },
      ],
    ],
  },
  {
    file: 'Week-38-Schedule.xlsx',
    day: '2026-09-13',
    count: 27,
    total: 27,
    mismatch: null,
    times: [
      ['9:30am', 1],
      ['9:50am', 12],
      ['9:55am', 9],
      ['11:30am', 4],
      ['12:15pm', 1],
    ],
    shared: 0,
    sample: [
      [
        0,
        {
          transporterId: 'AK92X3BJNUBTF',
          driverName: 'Carmen Abernathy',
          routeCode: '',
          dispatchTime: '9:50am',
          serviceType: 'Standard Parcel Electric - Rivian MEDIUM',
          routeDuration: '',
          vin: '',
          detail: '10 hrs',
          sharedDrivers: 'Carmen Abernathy',
          sharedIds: 'AK92X3BJNUBTF',
          pad: '',
        },
      ],
      [
        13,
        {
          transporterId: 'A0U9BOPMI0WOD9',
          driverName: 'Carmen Andre Hawthorne',
          routeCode: '',
          dispatchTime: '9:50am',
          serviceType: 'Nursery Route Level 1 - Electric Vehicle',
          routeDuration: '',
          vin: '',
          detail: '10 hrs',
          sharedDrivers: 'Carmen Andre Hawthorne',
          sharedIds: 'A0U9BOPMI0WOD9',
          pad: '',
        },
      ],
      [
        26,
        {
          transporterId: 'A1LSR7SEOTKE3I',
          driverName: 'Flora Orson Huxley',
          routeCode: '',
          dispatchTime: '9:55am',
          serviceType: 'Standard Parcel Electric - Rivian MEDIUM',
          routeDuration: '',
          vin: '',
          detail: '10 hrs',
          sharedDrivers: 'Flora Orson Huxley',
          sharedIds: 'A1LSR7SEOTKE3I',
          pad: '',
        },
      ],
    ],
  },
  {
    file: 'Week-38-Schedule.xlsx',
    day: '2026-09-14',
    count: 28,
    total: 28,
    mismatch: null,
    times: [
      ['9:50am', 16],
      ['9:55am', 12],
    ],
    shared: 0,
    sample: [
      [
        0,
        {
          transporterId: 'AK92X3BJNUBTF',
          driverName: 'Carmen Abernathy',
          routeCode: '',
          dispatchTime: '9:50am',
          serviceType: 'Standard Parcel Electric - Rivian MEDIUM',
          routeDuration: '',
          vin: '',
          detail: '10 hrs',
          sharedDrivers: 'Carmen Abernathy',
          sharedIds: 'AK92X3BJNUBTF',
          pad: '',
        },
      ],
      [
        14,
        {
          transporterId: 'A63AK2RYZDOMF0',
          driverName: 'Greta Bennett Eastwood',
          routeCode: '',
          dispatchTime: '9:50am',
          serviceType: 'Standard Parcel Electric - Rivian MEDIUM',
          routeDuration: '',
          vin: '',
          detail: '10 hrs',
          sharedDrivers: 'Greta Bennett Eastwood',
          sharedIds: 'A63AK2RYZDOMF0',
          pad: '',
        },
      ],
      [
        27,
        {
          transporterId: 'A72V4W2G2KLM6B',
          driverName: 'Darcy Rowan Danforth',
          routeCode: '',
          dispatchTime: '9:50am',
          serviceType: 'Standard Parcel Electric - Rivian MEDIUM',
          routeDuration: '',
          vin: '',
          detail: '10 hrs',
          sharedDrivers: 'Darcy Rowan Danforth',
          sharedIds: 'A72V4W2G2KLM6B',
          pad: '',
        },
      ],
    ],
  },
];

const SCHEDULE_REFUSALS: Array<{ file: string; day: string; error: string }> = [
  {
    file: 'Week-36-Schedule.xlsx',
    day: '2026-09-06',
    error: 'Nobody is rostered on Sun, 06/Sep in this schedule.',
  },
  {
    file: 'Week-38-Schedule.xlsx',
    day: '2026-09-15',
    error: 'Nobody is rostered on Tue, 15/Sep in this schedule.',
  },
  {
    file: 'Week-38-Schedule.xlsx',
    day: '2026-09-16',
    error: 'Nobody is rostered on Wed, 16/Sep in this schedule.',
  },
  {
    file: 'Week-38-Schedule.xlsx',
    day: '2026-09-17',
    error: 'Nobody is rostered on Thu, 17/Sep in this schedule.',
  },
  {
    file: 'Week-38-Schedule.xlsx',
    day: '2026-09-18',
    error: 'Nobody is rostered on Fri, 18/Sep in this schedule.',
  },
  {
    file: 'Week-38-Schedule.xlsx',
    day: '2026-09-19',
    error: 'Nobody is rostered on Sat, 19/Sep in this schedule.',
  },
  {
    file: 'Week-38-Schedule.xlsx',
    day: '2026-09-20',
    error:
      "This schedule doesn't cover Sunday, September 20 2026.\n\nThe weeks it has are: Sun, 13/Sep, Mon, 14/Sep, Tue, 15/Sep, Wed, 16/Sep, Thu, 17/Sep, Fri, 18/Sep, Sat, 19/Sep",
  },
  {
    file: 'Week-38-Schedule.xlsx',
    day: '2026-09-21',
    error:
      "This schedule doesn't cover Monday, September 21 2026.\n\nThe weeks it has are: Sun, 13/Sep, Mon, 14/Sep, Tue, 15/Sep, Wed, 16/Sep, Thu, 17/Sep, Fri, 18/Sep, Sat, 19/Sep",
  },
  {
    file: 'Week-38-Schedule.xlsx',
    day: '2026-09-22',
    error:
      "This schedule doesn't cover Tuesday, September 22 2026.\n\nThe weeks it has are: Sun, 13/Sep, Mon, 14/Sep, Tue, 15/Sep, Wed, 16/Sep, Thu, 17/Sep, Fri, 18/Sep, Sat, 19/Sep",
  },
  {
    file: 'Week-38-Schedule.xlsx',
    day: '2026-09-23',
    error:
      "This schedule doesn't cover Wednesday, September 23 2026.\n\nThe weeks it has are: Sun, 13/Sep, Mon, 14/Sep, Tue, 15/Sep, Wed, 16/Sep, Thu, 17/Sep, Fri, 18/Sep, Sat, 19/Sep",
  },
  {
    file: 'Week-38-Schedule.xlsx',
    day: '2026-09-24',
    error:
      "This schedule doesn't cover Thursday, September 24 2026.\n\nThe weeks it has are: Sun, 13/Sep, Mon, 14/Sep, Tue, 15/Sep, Wed, 16/Sep, Thu, 17/Sep, Fri, 18/Sep, Sat, 19/Sep",
  },
  {
    file: 'Week-38-Schedule.xlsx',
    day: '2026-09-25',
    error:
      "This schedule doesn't cover Friday, September 25 2026.\n\nThe weeks it has are: Sun, 13/Sep, Mon, 14/Sep, Tue, 15/Sep, Wed, 16/Sep, Thu, 17/Sep, Fri, 18/Sep, Sat, 19/Sep",
  },
  {
    file: 'Week-38-Schedule.xlsx',
    day: '2026-09-26',
    error:
      "This schedule doesn't cover Saturday, September 26 2026.\n\nThe weeks it has are: Sun, 13/Sep, Mon, 14/Sep, Tue, 15/Sep, Wed, 16/Sep, Thu, 17/Sep, Fri, 18/Sep, Sat, 19/Sep",
  },
];

describe('Routes and Itineraries fixtures', () => {
  it.each(FIXTURES)('reads $file', async (fixture) => {
    const dataSet = await importRouteExport(
      fixture.kind,
      fixturePath(fixture.folder, fixture.file),
    );
    expect(dataSet.kind).toBe(fixture.kind);
    expect(dataSet.rows).toHaveLength(fixture.count);
    expect(dataSet.day).toBe(fixture.day);
    expect(sharedRows(dataSet)).toHaveLength(fixture.shared);
    expect(dataSet.rows.filter((row) => row.routeDuration)).toHaveLength(fixture.durations);
    expect(dispatchTimes(dataSet)).toEqual(fixture.times);
    for (const [index, row] of fixture.sample) expect(dataSet.rows[index]).toEqual(row);
  });
});

describe('weekly schedule fixtures', () => {
  it.each(SCHEDULE_FIXTURES)('reads $file for $day', async (fixture) => {
    const dataSet = await importRouteExport(
      'schedule',
      fixturePath('schedules', fixture.file),
      fixture.day,
    );
    expect(dataSet.kind).toBe('schedule');
    expect(dataSet.day).toBe(fixture.day);
    expect(dataSet.rows).toHaveLength(fixture.count);
    expect(dataSet.sourceTotal).toBe(fixture.total);
    expect(totalMismatch(dataSet)).toBe(fixture.mismatch);
    expect(sharedRows(dataSet)).toHaveLength(fixture.shared);
    expect(dispatchTimes(dataSet)).toEqual(fixture.times);
    for (const [index, row] of fixture.sample) expect(dataSet.rows[index]).toEqual(row);
  });

  it.each(SCHEDULE_REFUSALS)('refuses $file for $day', async (fixture) => {
    await expect(
      importRouteExport('schedule', fixturePath('schedules', fixture.file), fixture.day),
    ).rejects.toThrow(new RouteDataImportError(fixture.error));
  });
});

describe('route export refusals that carry the file', () => {
  it('says so when the file is not there', async () => {
    await expect(importRouteExport('routes', join('nowhere', 'missing.xlsx'))).rejects.toThrow(
      new RouteDataImportError(`File not found:\n\n${join('nowhere', 'missing.xlsx')}`),
    );
  });

  it('says so when the file is not a workbook', async () => {
    await withScenarioFile(
      { file: 'not-a-workbook.xlsx', text: 'just some words' },
      async (path) => {
        await expect(importRouteExport('itineraries', path)).rejects.toThrow(
          /^Couldn't open the workbook:\n\n/,
        );
      },
    );
  });

  it('refuses a kind it does not know', async () => {
    await withScenarioFile(
      { file: 'routes.xlsx', sheets: [{ name: 'Sheet1', rows: [['x']] }] },
      async (path) => {
        await expect(importRouteExport('foo', path)).rejects.toThrow(
          new RouteDataImportError('Unknown export type: foo'),
        );
      },
    );
  });
});

describe('the weekly schedule without a day', () => {
  it('reads today', async () => {
    vi.useFakeTimers({ toFake: ['Date'] });
    try {
      vi.setSystemTime(new Date(2026, 7, 4, 12, 0, 0));
      const scenario = SCENARIOS.find(([spec]) => spec.day === '2026-08-04');
      expect(scenario).toBeDefined();
      const [spec, expected] = scenario as [Scenario, Record<string, unknown>];
      const withoutDay: Scenario = { ...spec };
      delete withoutDay.day;
      expect(await runScenario(withoutDay)).toEqual(expected);
    } finally {
      vi.useRealTimers();
    }
  });
});

const SCENARIOS: Array<[Scenario, Record<string, unknown>]> = [
  [
    {
      name: 'shared routes, placeholders, clock spellings',
      importer: 'routes',
      file: 'Routes_XXX1_2026-08-04_15_15 (CDT).xlsx',
      sheets: [
        {
          name: 'Sheet1',
          rows: [
            ['Routes export'],
            [
              'Route code',
              'DSP',
              'Transporter Id',
              'Driver name',
              'Route progress',
              'Delivery Service Type',
              'Route Duration',
              'Planned Departure Time',
            ],
            [
              'CX1',
              'Team',
              'T001',
              'Carmen Abernathy',
              'ON_TIME',
              'Standard Parcel Electric - Rivian MEDIUM',
              417,
              '10:20am',
            ],
            [
              'CX2',
              'Team',
              'T002|T003',
              'Nadine Abernathy|Nolan Abernathy',
              'COMPLETE',
              'Standard Parcel Step Van - US (440 mins)',
              485,
              '9:50 AM',
            ],
            [
              'Missing',
              'Team',
              'T004',
              'Ainsworth, Barrett',
              'n/a',
              'Standard Parcel - Large Van (30 minutes.)',
              1,
              '9:50',
            ],
            [
              'CX4',
              'Team',
              'T005',
              null,
              'AT_RISK',
              'DSP Initiated Work (  12  Min )',
              1,
              {
                time: '10:25',
              },
            ],
            [
              'CX5',
              'Team',
              null,
              'Zane Applewhite',
              'AT_RISK',
              null,
              1,
              {
                datetime: '2026-08-04 13:05',
              },
            ],
            ['CX6', 'Team', 'T006|T007|', 'Elodie Ashdown|', 'Missing', 'None', 1, 'Missing'],
            [
              'CX7',
              'Team',
              '|T008',
              '|Hadley Ashdown',
              '-',
              'Service (440 mins) trailing',
              1,
              '12:00 PM',
            ],
            ['CX8', 'Team', 'T009', 'Xavier Bannister', 'x', 'Service (440 mins)', 1, '12:05am'],
            [null, null, null, null, null, null, null, null],
            ['CX9', 'Team', 'NA', 'none', 'x', 'y', 1, 'z'],
            ['CX10', 'Team', 'T010', 'Yara Beaumont', 'x', 'y', 1, '9:75am'],
          ],
        },
      ],
    },
    {
      kind: 'routes',
      day: '2026-08-04',
      sourceTotal: null,
      rows: [
        {
          transporterId: 'T001',
          driverName: 'Carmen Abernathy',
          routeCode: 'CX1',
          dispatchTime: '10:20am',
          serviceType: 'Standard Parcel Electric - Rivian MEDIUM',
          routeDuration: '',
          vin: '',
          detail: 'ON_TIME',
          sharedDrivers: 'Carmen Abernathy',
          sharedIds: 'T001',
          pad: '',
        },
        {
          transporterId: 'T002',
          driverName: 'Nadine Abernathy',
          routeCode: 'CX2',
          dispatchTime: '9:50am',
          serviceType: 'Standard Parcel Step Van - US',
          routeDuration: '440 mins',
          vin: '',
          detail: 'COMPLETE',
          sharedDrivers: 'Nadine Abernathy|Nolan Abernathy',
          sharedIds: 'T002|T003',
          pad: '',
        },
        {
          transporterId: 'T004',
          driverName: 'Ainsworth Barrett',
          routeCode: '',
          dispatchTime: '9:50',
          serviceType: 'Standard Parcel - Large Van',
          routeDuration: '30 mins',
          vin: '',
          detail: '',
          sharedDrivers: 'Ainsworth Barrett',
          sharedIds: 'T004',
          pad: '',
        },
        {
          transporterId: 'T005',
          driverName: '',
          routeCode: 'CX4',
          dispatchTime: '10:25am',
          serviceType: 'DSP Initiated Work',
          routeDuration: '12 mins',
          vin: '',
          detail: 'AT_RISK',
          sharedDrivers: '',
          sharedIds: 'T005',
          pad: '',
        },
        {
          transporterId: '',
          driverName: 'Zane Applewhite',
          routeCode: 'CX5',
          dispatchTime: '1:05pm',
          serviceType: '',
          routeDuration: '',
          vin: '',
          detail: 'AT_RISK',
          sharedDrivers: 'Zane Applewhite',
          sharedIds: '',
          pad: '',
        },
        {
          transporterId: 'T006',
          driverName: 'Elodie Ashdown',
          routeCode: 'CX6',
          dispatchTime: '',
          serviceType: '',
          routeDuration: '',
          vin: '',
          detail: '',
          sharedDrivers: 'Elodie Ashdown',
          sharedIds: 'T006|T007',
          pad: '',
        },
        {
          transporterId: 'T008',
          driverName: 'Hadley Ashdown',
          routeCode: 'CX7',
          dispatchTime: '12:00pm',
          serviceType: 'Service (440 mins) trailing',
          routeDuration: '',
          vin: '',
          detail: '',
          sharedDrivers: 'Hadley Ashdown',
          sharedIds: 'T008',
          pad: '',
        },
        {
          transporterId: 'T009',
          driverName: 'Xavier Bannister',
          routeCode: 'CX8',
          dispatchTime: '12:05am',
          serviceType: 'Service',
          routeDuration: '440 mins',
          vin: '',
          detail: 'x',
          sharedDrivers: 'Xavier Bannister',
          sharedIds: 'T009',
          pad: '',
        },
        {
          transporterId: 'T010',
          driverName: 'Yara Beaumont',
          routeCode: 'CX10',
          dispatchTime: '9:75am',
          serviceType: 'y',
          routeDuration: '',
          vin: '',
          detail: 'x',
          sharedDrivers: 'Yara Beaumont',
          sharedIds: 'T010',
          pad: '',
        },
      ],
    },
  ],
  [
    {
      name: 'a file name with no usable date',
      importer: 'routes',
      file: 'Routes_XXX1_2026-13-45_15_15.xlsx',
      sheets: [
        {
          name: 'Sheet1',
          rows: [
            [
              'Route code',
              'DSP',
              'Transporter Id',
              'Driver name',
              'Route progress',
              'Delivery Service Type',
              'Route Duration',
              'Planned Departure Time',
            ],
            ['CX1', 'Team', 'T001', 'Carmen Abernathy', 'ON_TIME', 'Standard Parcel', 1, '10:20am'],
          ],
        },
      ],
    },
    {
      kind: 'routes',
      day: null,
      sourceTotal: null,
      rows: [
        {
          transporterId: 'T001',
          driverName: 'Carmen Abernathy',
          routeCode: 'CX1',
          dispatchTime: '10:20am',
          serviceType: 'Standard Parcel',
          routeDuration: '',
          vin: '',
          detail: 'ON_TIME',
          sharedDrivers: 'Carmen Abernathy',
          sharedIds: 'T001',
          pad: '',
        },
      ],
    },
  ],
  [
    {
      name: 'a file name with an underscore date',
      importer: 'routes',
      file: 'Routes_XXX1_2026_08_04.xlsx',
      sheets: [
        {
          name: 'Sheet1',
          rows: [
            [
              'Route code',
              'DSP',
              'Transporter Id',
              'Driver name',
              'Route progress',
              'Delivery Service Type',
              'Route Duration',
              'Planned Departure Time',
            ],
            ['CX1', 'Team', 'T001', 'Carmen Abernathy', 'ON_TIME', 'Standard Parcel', 1, '10:20am'],
          ],
        },
      ],
    },
    {
      kind: 'routes',
      day: '2026-08-04',
      sourceTotal: null,
      rows: [
        {
          transporterId: 'T001',
          driverName: 'Carmen Abernathy',
          routeCode: 'CX1',
          dispatchTime: '10:20am',
          serviceType: 'Standard Parcel',
          routeDuration: '',
          vin: '',
          detail: 'ON_TIME',
          sharedDrivers: 'Carmen Abernathy',
          sharedIds: 'T001',
          pad: '',
        },
      ],
    },
  ],
  [
    {
      name: 'header found on the second sheet',
      importer: 'routes',
      file: 'routes.xlsx',
      sheets: [
        {
          name: 'Empty',
          rows: [],
        },
        {
          name: 'Routes',
          rows: [
            [
              'Route code',
              'DSP',
              'Transporter Id',
              'Driver name',
              'Route progress',
              'Delivery Service Type',
              'Route Duration',
              'Planned Departure Time',
            ],
            ['CX1', 'Team', 'T001', 'Carmen Abernathy', 'ON_TIME', 'Standard Parcel', 1, '10:20am'],
          ],
        },
      ],
    },
    {
      kind: 'routes',
      day: null,
      sourceTotal: null,
      rows: [
        {
          transporterId: 'T001',
          driverName: 'Carmen Abernathy',
          routeCode: 'CX1',
          dispatchTime: '10:20am',
          serviceType: 'Standard Parcel',
          routeDuration: '',
          vin: '',
          detail: 'ON_TIME',
          sharedDrivers: 'Carmen Abernathy',
          sharedIds: 'T001',
          pad: '',
        },
      ],
    },
  ],
  [
    {
      name: 'alias headers',
      importer: 'routes',
      file: 'routes.xlsx',
      sheets: [
        {
          name: 'Sheet1',
          rows: [
            ['Route', 'Transporter', 'Driver', 'Progress', 'Service Type', 'Departure Time'],
            ['CX1', 'T001', 'Carmen Abernathy', 'ON_TIME', 'Standard Parcel', '10:20am'],
          ],
        },
      ],
    },
    {
      kind: 'routes',
      day: null,
      sourceTotal: null,
      rows: [
        {
          transporterId: 'T001',
          driverName: 'Carmen Abernathy',
          routeCode: 'CX1',
          dispatchTime: '10:20am',
          serviceType: 'Standard Parcel',
          routeDuration: '',
          vin: '',
          detail: 'ON_TIME',
          sharedDrivers: 'Carmen Abernathy',
          sharedIds: 'T001',
          pad: '',
        },
      ],
    },
  ],
  [
    {
      name: 'no header row',
      importer: 'routes',
      file: 'routes.xlsx',
      sheets: [
        {
          name: 'Sheet1',
          rows: [
            ['Route code', 'Driver name'],
            ['CX1', 'Carmen Abernathy'],
          ],
        },
      ],
    },
    {
      error:
        "Couldn't find the header row on any sheet.\n\nExpected a row containing 'Transporter Id' and 'Planned Departure Time' - is this a Routes export?",
    },
  ],
  [
    {
      name: 'a header and no rows',
      importer: 'routes',
      file: 'routes.xlsx',
      sheets: [
        {
          name: 'Sheet1',
          rows: [
            [
              'Route code',
              'DSP',
              'Transporter Id',
              'Driver name',
              'Route progress',
              'Delivery Service Type',
              'Route Duration',
              'Planned Departure Time',
            ],
            [null, null, null, null, null, null, null, null],
          ],
        },
      ],
    },
    {
      error: 'Found the header row but no route rows below it.',
    },
  ],
  [
    {
      name: 'morning export on a second sheet, duration split off',
      importer: 'itineraries',
      file: 'Itineraries_XXX1_2026-08-04_06_00 (CDT).xlsx',
      sheets: [
        {
          name: 'Itineraries',
          rows: [],
        },
        {
          name: 'Pre Dispatch',
          rows: [
            [
              'Transporter Id',
              'Driver name',
              'DSP',
              'Route code',
              'Progress Status',
              'Delivery Service Type',
            ],
            [
              'T001',
              'Carmen,Abernathy',
              'Team',
              'CX1',
              'NOT_STARTED',
              'Standard Parcel Electric - Rivian MEDIUM (440 mins)',
            ],
            [
              'T002|T003',
              'Nadine,Abernathy|Nolan,Abernathy',
              'Team',
              'CX2|CX3',
              'NOT_STARTED',
              'Standard Parcel Step Van - US (465 mins)',
            ],
          ],
        },
      ],
    },
    {
      kind: 'itineraries',
      day: '2026-08-04',
      sourceTotal: null,
      rows: [
        {
          transporterId: 'T001',
          driverName: 'Carmen Abernathy',
          routeCode: 'CX1',
          dispatchTime: '',
          serviceType: 'Standard Parcel Electric - Rivian MEDIUM',
          routeDuration: '440 mins',
          vin: '',
          detail: '',
          sharedDrivers: 'Carmen Abernathy',
          sharedIds: 'T001',
          pad: '',
        },
        {
          transporterId: 'T002',
          driverName: 'Nadine Abernathy',
          routeCode: 'CX2|CX3',
          dispatchTime: '',
          serviceType: 'Standard Parcel Step Van - US',
          routeDuration: '465 mins',
          vin: '',
          detail: '',
          sharedDrivers: 'Nadine Abernathy|Nolan Abernathy',
          sharedIds: 'T002|T003',
          pad: '',
        },
      ],
    },
  ],
  [
    {
      name: 'afternoon export with VIN and actual departure',
      importer: 'itineraries',
      file: 'Itineraries_XXX1_2026-08-04_21_36 (CDT).xlsx',
      sheets: [
        {
          name: 'Sheet1',
          rows: [
            [
              'Transporter Id',
              'Driver name',
              'DSP',
              'Route code',
              'Progress Status',
              'Delivery Service Type',
              'cortex_vin_number',
              'Actual Departure',
            ],
            [
              'T001',
              'Carmen,Abernathy',
              'Team',
              'CX1',
              'COMPLETE',
              'Standard Parcel Electric',
              'VINC1',
              '6:41 PM',
            ],
            [
              'T002',
              'Nadine Abernathy',
              'Team',
              'CX2',
              'COMPLETE',
              'Standard Parcel Electric',
              'Missing',
              {
                time: '18:03',
              },
            ],
            [
              'T003',
              'Nolan Abernathy',
              'Team',
              'CX3',
              'COMPLETE',
              'Standard Parcel Electric',
              null,
              'Missing',
            ],
            [
              'T004',
              'Barrett Ainsworth',
              'Team',
              'CX4',
              'COMPLETE',
              'Standard Parcel Electric',
              'VINC4',
              'soon',
            ],
          ],
        },
      ],
    },
    {
      kind: 'itineraries',
      day: '2026-08-04',
      sourceTotal: null,
      rows: [
        {
          transporterId: 'T001',
          driverName: 'Carmen Abernathy',
          routeCode: 'CX1',
          dispatchTime: '',
          serviceType: 'Standard Parcel Electric',
          routeDuration: '',
          vin: 'VINC1',
          detail: '6:41pm',
          sharedDrivers: 'Carmen Abernathy',
          sharedIds: 'T001',
          pad: '',
        },
        {
          transporterId: 'T002',
          driverName: 'Nadine Abernathy',
          routeCode: 'CX2',
          dispatchTime: '',
          serviceType: 'Standard Parcel Electric',
          routeDuration: '',
          vin: '',
          detail: '6:03pm',
          sharedDrivers: 'Nadine Abernathy',
          sharedIds: 'T002',
          pad: '',
        },
        {
          transporterId: 'T003',
          driverName: 'Nolan Abernathy',
          routeCode: 'CX3',
          dispatchTime: '',
          serviceType: 'Standard Parcel Electric',
          routeDuration: '',
          vin: '',
          detail: '',
          sharedDrivers: 'Nolan Abernathy',
          sharedIds: 'T003',
          pad: '',
        },
        {
          transporterId: 'T004',
          driverName: 'Barrett Ainsworth',
          routeCode: 'CX4',
          dispatchTime: '',
          serviceType: 'Standard Parcel Electric',
          routeDuration: '',
          vin: 'VINC4',
          detail: 'soon',
          sharedDrivers: 'Barrett Ainsworth',
          sharedIds: 'T004',
          pad: '',
        },
      ],
    },
  ],
  [
    {
      name: 'header needs the route code',
      importer: 'itineraries',
      file: 'itineraries.xlsx',
      sheets: [
        {
          name: 'Sheet1',
          rows: [
            ['Transporter Id', 'Driver name'],
            ['T001', 'Carmen Abernathy'],
          ],
        },
      ],
    },
    {
      error:
        "Couldn't find the header row on any sheet.\n\nExpected a row containing 'Transporter Id' and 'Route code' - is this a Itineraries export?",
    },
  ],
  [
    {
      name: 'a header and no rows',
      importer: 'itineraries',
      file: 'itineraries.xlsx',
      sheets: [
        {
          name: 'Sheet1',
          rows: [
            [
              'Transporter Id',
              'Driver name',
              'DSP',
              'Route code',
              'Progress Status',
              'Delivery Service Type',
              'cortex_vin_number',
              'Actual Departure',
            ],
            [null, null, null, null, null, null, null, null],
          ],
        },
      ],
    },
    {
      error: 'Found the header row but no route rows below it.',
    },
  ],
  [
    {
      name: 'Tuesday: blocks, bullets, shared names and a headcount',
      importer: 'schedule',
      file: 'Week-32-Schedule.xlsx',
      sheets: [
        {
          name: 'Shifts & Availability',
          rows: [],
        },
        {
          name: 'Rostered Work Blocks',
          rows: [
            ['Rostered Work Blocks'],
            ['Week 32, 2026'],
            [],
            [
              'Associate Name',
              'Transporter ID',
              'Mon, 03/Aug',
              'Tue, 04/Aug',
              'Wed, 05/August',
              'Thu, 06/Foo',
              'Fri, 07/Aug',
            ],
            [
              'Carmen Abernathy',
              'T001',
              'Standard Parcel Step Van - US\n9:55am - 10 hrs',
              'Standard Parcel Step Van - US\n9:55am \u2022 10 hrs',
              null,
              'x',
              null,
            ],
            [
              'Nadine Abernathy',
              'T002',
              '9:50am - 10 hrs',
              '9:50 AM \u00b7 9 hrs \u00b7 break',
              'Service only',
              'x',
              null,
            ],
            [
              'Nolan Abernathy|Barrett Ainsworth',
              'T003|T004',
              null,
              'Electric\r\n10:05 AM | 8 hrs\nextra line',
              '  ',
              'x',
              null,
            ],
            ['Colton Alderman', 'T005', null, '\n', 'Standard Parcel\n\n10:25am', 'x', null],
            [null, 'T006', null, 'Ghost row', null, 'x', null],
            [
              'Zane Applewhite',
              null,
              null,
              'Standard Parcel Electric\n11:00pm \u2022 12:30 hrs',
              null,
              'x',
              null,
            ],
            ['Total Rostered', null, 3, 12.0, 7, 'x', null],
            [],
            ['Elodie Ashdown', 'T007', null, 'Late row after total', null, 'x', null],
            ['Total Rostered again', null, 1, 5, null, 'x', null],
          ],
        },
      ],
      day: '2026-08-04',
    },
    {
      kind: 'schedule',
      day: '2026-08-04',
      sourceTotal: 5,
      rows: [
        {
          transporterId: 'T001',
          driverName: 'Carmen Abernathy',
          routeCode: '',
          dispatchTime: '9:55am',
          serviceType: 'Standard Parcel Step Van - US',
          routeDuration: '',
          vin: '',
          detail: '10 hrs',
          sharedDrivers: 'Carmen Abernathy',
          sharedIds: 'T001',
          pad: '',
        },
        {
          transporterId: 'T002',
          driverName: 'Nadine Abernathy',
          routeCode: '',
          dispatchTime: '9:50am',
          serviceType: '',
          routeDuration: '',
          vin: '',
          detail: '9 hrs break',
          sharedDrivers: 'Nadine Abernathy',
          sharedIds: 'T002',
          pad: '',
        },
        {
          transporterId: 'T003',
          driverName: 'Nolan Abernathy',
          routeCode: '',
          dispatchTime: '10:05am',
          serviceType: 'Electric',
          routeDuration: '',
          vin: '',
          detail: '8 hrs',
          sharedDrivers: 'Nolan Abernathy|Barrett Ainsworth',
          sharedIds: 'T003|T004',
          pad: '',
        },
        {
          transporterId: '',
          driverName: 'Zane Applewhite',
          routeCode: '',
          dispatchTime: '11:00pm',
          serviceType: 'Standard Parcel Electric',
          routeDuration: '',
          vin: '',
          detail: '12:30 hrs',
          sharedDrivers: 'Zane Applewhite',
          sharedIds: '',
          pad: '',
        },
        {
          transporterId: 'T007',
          driverName: 'Elodie Ashdown',
          routeCode: '',
          dispatchTime: '',
          serviceType: 'Late row after total',
          routeDuration: '',
          vin: '',
          detail: '',
          sharedDrivers: 'Elodie Ashdown',
          sharedIds: 'T007',
          pad: '',
        },
      ],
    },
  ],
  [
    {
      name: 'the year in the day does not matter',
      importer: 'schedule',
      file: 'Week-32-Schedule.xlsx',
      sheets: [
        {
          name: 'Rostered Work Blocks',
          rows: [
            ['Rostered Work Blocks'],
            ['Week 32, 2026'],
            [],
            [
              'Associate Name',
              'Transporter ID',
              'Mon, 03/Aug',
              'Tue, 04/Aug',
              'Wed, 05/August',
              'Thu, 06/Foo',
              'Fri, 07/Aug',
            ],
            [
              'Carmen Abernathy',
              'T001',
              'Standard Parcel Step Van - US\n9:55am - 10 hrs',
              'Standard Parcel Step Van - US\n9:55am \u2022 10 hrs',
              null,
              'x',
              null,
            ],
            [
              'Nadine Abernathy',
              'T002',
              '9:50am - 10 hrs',
              '9:50 AM \u00b7 9 hrs \u00b7 break',
              'Service only',
              'x',
              null,
            ],
            [
              'Nolan Abernathy|Barrett Ainsworth',
              'T003|T004',
              null,
              'Electric\r\n10:05 AM | 8 hrs\nextra line',
              '  ',
              'x',
              null,
            ],
            ['Colton Alderman', 'T005', null, '\n', 'Standard Parcel\n\n10:25am', 'x', null],
            [null, 'T006', null, 'Ghost row', null, 'x', null],
            [
              'Zane Applewhite',
              null,
              null,
              'Standard Parcel Electric\n11:00pm \u2022 12:30 hrs',
              null,
              'x',
              null,
            ],
            ['Total Rostered', null, 3, 12.0, 7, 'x', null],
            [],
            ['Elodie Ashdown', 'T007', null, 'Late row after total', null, 'x', null],
            ['Total Rostered again', null, 1, 5, null, 'x', null],
          ],
        },
      ],
      day: '2031-08-04',
    },
    {
      kind: 'schedule',
      day: '2031-08-04',
      sourceTotal: 5,
      rows: [
        {
          transporterId: 'T001',
          driverName: 'Carmen Abernathy',
          routeCode: '',
          dispatchTime: '9:55am',
          serviceType: 'Standard Parcel Step Van - US',
          routeDuration: '',
          vin: '',
          detail: '10 hrs',
          sharedDrivers: 'Carmen Abernathy',
          sharedIds: 'T001',
          pad: '',
        },
        {
          transporterId: 'T002',
          driverName: 'Nadine Abernathy',
          routeCode: '',
          dispatchTime: '9:50am',
          serviceType: '',
          routeDuration: '',
          vin: '',
          detail: '9 hrs break',
          sharedDrivers: 'Nadine Abernathy',
          sharedIds: 'T002',
          pad: '',
        },
        {
          transporterId: 'T003',
          driverName: 'Nolan Abernathy',
          routeCode: '',
          dispatchTime: '10:05am',
          serviceType: 'Electric',
          routeDuration: '',
          vin: '',
          detail: '8 hrs',
          sharedDrivers: 'Nolan Abernathy|Barrett Ainsworth',
          sharedIds: 'T003|T004',
          pad: '',
        },
        {
          transporterId: '',
          driverName: 'Zane Applewhite',
          routeCode: '',
          dispatchTime: '11:00pm',
          serviceType: 'Standard Parcel Electric',
          routeDuration: '',
          vin: '',
          detail: '12:30 hrs',
          sharedDrivers: 'Zane Applewhite',
          sharedIds: '',
          pad: '',
        },
        {
          transporterId: 'T007',
          driverName: 'Elodie Ashdown',
          routeCode: '',
          dispatchTime: '',
          serviceType: 'Late row after total',
          routeDuration: '',
          vin: '',
          detail: '',
          sharedDrivers: 'Elodie Ashdown',
          sharedIds: 'T007',
          pad: '',
        },
      ],
    },
  ],
  [
    {
      name: 'Monday has nobody but a headcount',
      importer: 'schedule',
      file: 'Week-32-Schedule.xlsx',
      sheets: [
        {
          name: 'Rostered Work Blocks',
          rows: [
            ['Rostered Work Blocks'],
            ['Week 32, 2026'],
            [],
            [
              'Associate Name',
              'Transporter ID',
              'Mon, 03/Aug',
              'Tue, 04/Aug',
              'Wed, 05/August',
              'Thu, 06/Foo',
              'Fri, 07/Aug',
            ],
            [
              'Carmen Abernathy',
              'T001',
              'Standard Parcel Step Van - US\n9:55am - 10 hrs',
              'Standard Parcel Step Van - US\n9:55am \u2022 10 hrs',
              null,
              'x',
              null,
            ],
            [
              'Nadine Abernathy',
              'T002',
              '9:50am - 10 hrs',
              '9:50 AM \u00b7 9 hrs \u00b7 break',
              'Service only',
              'x',
              null,
            ],
            [
              'Nolan Abernathy|Barrett Ainsworth',
              'T003|T004',
              null,
              'Electric\r\n10:05 AM | 8 hrs\nextra line',
              '  ',
              'x',
              null,
            ],
            ['Colton Alderman', 'T005', null, '\n', 'Standard Parcel\n\n10:25am', 'x', null],
            [null, 'T006', null, 'Ghost row', null, 'x', null],
            [
              'Zane Applewhite',
              null,
              null,
              'Standard Parcel Electric\n11:00pm \u2022 12:30 hrs',
              null,
              'x',
              null,
            ],
            ['Total Rostered', null, 3, 12.0, 7, 'x', null],
            [],
            ['Elodie Ashdown', 'T007', null, 'Late row after total', null, 'x', null],
            ['Total Rostered again', null, 1, 5, null, 'x', null],
          ],
        },
      ],
      day: '2026-08-03',
    },
    {
      kind: 'schedule',
      day: '2026-08-03',
      sourceTotal: 1,
      rows: [
        {
          transporterId: 'T001',
          driverName: 'Carmen Abernathy',
          routeCode: '',
          dispatchTime: '9:55am',
          serviceType: 'Standard Parcel Step Van - US',
          routeDuration: '',
          vin: '',
          detail: '',
          sharedDrivers: 'Carmen Abernathy',
          sharedIds: 'T001',
          pad: '',
        },
        {
          transporterId: 'T002',
          driverName: 'Nadine Abernathy',
          routeCode: '',
          dispatchTime: '9:50am',
          serviceType: '',
          routeDuration: '',
          vin: '',
          detail: '',
          sharedDrivers: 'Nadine Abernathy',
          sharedIds: 'T002',
          pad: '',
        },
      ],
    },
  ],
  [
    {
      name: 'a long month name in the heading',
      importer: 'schedule',
      file: 'Week-32-Schedule.xlsx',
      sheets: [
        {
          name: 'Rostered Work Blocks',
          rows: [
            ['Rostered Work Blocks'],
            ['Week 32, 2026'],
            [],
            [
              'Associate Name',
              'Transporter ID',
              'Mon, 03/Aug',
              'Tue, 04/Aug',
              'Wed, 05/August',
              'Thu, 06/Foo',
              'Fri, 07/Aug',
            ],
            [
              'Carmen Abernathy',
              'T001',
              'Standard Parcel Step Van - US\n9:55am - 10 hrs',
              'Standard Parcel Step Van - US\n9:55am \u2022 10 hrs',
              null,
              'x',
              null,
            ],
            [
              'Nadine Abernathy',
              'T002',
              '9:50am - 10 hrs',
              '9:50 AM \u00b7 9 hrs \u00b7 break',
              'Service only',
              'x',
              null,
            ],
            [
              'Nolan Abernathy|Barrett Ainsworth',
              'T003|T004',
              null,
              'Electric\r\n10:05 AM | 8 hrs\nextra line',
              '  ',
              'x',
              null,
            ],
            ['Colton Alderman', 'T005', null, '\n', 'Standard Parcel\n\n10:25am', 'x', null],
            [null, 'T006', null, 'Ghost row', null, 'x', null],
            [
              'Zane Applewhite',
              null,
              null,
              'Standard Parcel Electric\n11:00pm \u2022 12:30 hrs',
              null,
              'x',
              null,
            ],
            ['Total Rostered', null, 3, 12.0, 7, 'x', null],
            [],
            ['Elodie Ashdown', 'T007', null, 'Late row after total', null, 'x', null],
            ['Total Rostered again', null, 1, 5, null, 'x', null],
          ],
        },
      ],
      day: '2026-08-05',
    },
    {
      kind: 'schedule',
      day: '2026-08-05',
      sourceTotal: null,
      rows: [
        {
          transporterId: 'T002',
          driverName: 'Nadine Abernathy',
          routeCode: '',
          dispatchTime: '',
          serviceType: 'Service only',
          routeDuration: '',
          vin: '',
          detail: '',
          sharedDrivers: 'Nadine Abernathy',
          sharedIds: 'T002',
          pad: '',
        },
        {
          transporterId: 'T005',
          driverName: 'Colton Alderman',
          routeCode: '',
          dispatchTime: '10:25am',
          serviceType: 'Standard Parcel',
          routeDuration: '',
          vin: '',
          detail: '',
          sharedDrivers: 'Colton Alderman',
          sharedIds: 'T005',
          pad: '',
        },
      ],
    },
  ],
  [
    {
      name: 'an unknown month in the heading is not a day column',
      importer: 'schedule',
      file: 'Week-32-Schedule.xlsx',
      sheets: [
        {
          name: 'Rostered Work Blocks',
          rows: [
            ['Rostered Work Blocks'],
            ['Week 32, 2026'],
            [],
            [
              'Associate Name',
              'Transporter ID',
              'Mon, 03/Aug',
              'Tue, 04/Aug',
              'Wed, 05/August',
              'Thu, 06/Foo',
              'Fri, 07/Aug',
            ],
            [
              'Carmen Abernathy',
              'T001',
              'Standard Parcel Step Van - US\n9:55am - 10 hrs',
              'Standard Parcel Step Van - US\n9:55am \u2022 10 hrs',
              null,
              'x',
              null,
            ],
            [
              'Nadine Abernathy',
              'T002',
              '9:50am - 10 hrs',
              '9:50 AM \u00b7 9 hrs \u00b7 break',
              'Service only',
              'x',
              null,
            ],
            [
              'Nolan Abernathy|Barrett Ainsworth',
              'T003|T004',
              null,
              'Electric\r\n10:05 AM | 8 hrs\nextra line',
              '  ',
              'x',
              null,
            ],
            ['Colton Alderman', 'T005', null, '\n', 'Standard Parcel\n\n10:25am', 'x', null],
            [null, 'T006', null, 'Ghost row', null, 'x', null],
            [
              'Zane Applewhite',
              null,
              null,
              'Standard Parcel Electric\n11:00pm \u2022 12:30 hrs',
              null,
              'x',
              null,
            ],
            ['Total Rostered', null, 3, 12.0, 7, 'x', null],
            [],
            ['Elodie Ashdown', 'T007', null, 'Late row after total', null, 'x', null],
            ['Total Rostered again', null, 1, 5, null, 'x', null],
          ],
        },
      ],
      day: '2026-06-06',
    },
    {
      error:
        "This schedule doesn't cover Saturday, June 06 2026.\n\nThe weeks it has are: Mon, 03/Aug, Tue, 04/Aug, Wed, 05/August, Fri, 07/Aug",
    },
  ],
  [
    {
      name: 'a day with nobody rostered',
      importer: 'schedule',
      file: 'Week-32-Schedule.xlsx',
      sheets: [
        {
          name: 'Rostered Work Blocks',
          rows: [
            ['Rostered Work Blocks'],
            ['Week 32, 2026'],
            [],
            [
              'Associate Name',
              'Transporter ID',
              'Mon, 03/Aug',
              'Tue, 04/Aug',
              'Wed, 05/August',
              'Thu, 06/Foo',
              'Fri, 07/Aug',
            ],
            [
              'Carmen Abernathy',
              'T001',
              'Standard Parcel Step Van - US\n9:55am - 10 hrs',
              'Standard Parcel Step Van - US\n9:55am \u2022 10 hrs',
              null,
              'x',
              null,
            ],
            [
              'Nadine Abernathy',
              'T002',
              '9:50am - 10 hrs',
              '9:50 AM \u00b7 9 hrs \u00b7 break',
              'Service only',
              'x',
              null,
            ],
            [
              'Nolan Abernathy|Barrett Ainsworth',
              'T003|T004',
              null,
              'Electric\r\n10:05 AM | 8 hrs\nextra line',
              '  ',
              'x',
              null,
            ],
            ['Colton Alderman', 'T005', null, '\n', 'Standard Parcel\n\n10:25am', 'x', null],
            [null, 'T006', null, 'Ghost row', null, 'x', null],
            [
              'Zane Applewhite',
              null,
              null,
              'Standard Parcel Electric\n11:00pm \u2022 12:30 hrs',
              null,
              'x',
              null,
            ],
            ['Total Rostered', null, 3, 12.0, 7, 'x', null],
            [],
            ['Elodie Ashdown', 'T007', null, 'Late row after total', null, 'x', null],
            ['Total Rostered again', null, 1, 5, null, 'x', null],
          ],
        },
      ],
      day: '2026-08-07',
    },
    {
      error: 'Nobody is rostered on Fri, 07/Aug in this schedule.',
    },
  ],
  [
    {
      name: 'a day the file does not cover',
      importer: 'schedule',
      file: 'Week-32-Schedule.xlsx',
      sheets: [
        {
          name: 'Rostered Work Blocks',
          rows: [
            ['Rostered Work Blocks'],
            ['Week 32, 2026'],
            [],
            [
              'Associate Name',
              'Transporter ID',
              'Mon, 03/Aug',
              'Tue, 04/Aug',
              'Wed, 05/August',
              'Thu, 06/Foo',
              'Fri, 07/Aug',
            ],
            [
              'Carmen Abernathy',
              'T001',
              'Standard Parcel Step Van - US\n9:55am - 10 hrs',
              'Standard Parcel Step Van - US\n9:55am \u2022 10 hrs',
              null,
              'x',
              null,
            ],
            [
              'Nadine Abernathy',
              'T002',
              '9:50am - 10 hrs',
              '9:50 AM \u00b7 9 hrs \u00b7 break',
              'Service only',
              'x',
              null,
            ],
            [
              'Nolan Abernathy|Barrett Ainsworth',
              'T003|T004',
              null,
              'Electric\r\n10:05 AM | 8 hrs\nextra line',
              '  ',
              'x',
              null,
            ],
            ['Colton Alderman', 'T005', null, '\n', 'Standard Parcel\n\n10:25am', 'x', null],
            [null, 'T006', null, 'Ghost row', null, 'x', null],
            [
              'Zane Applewhite',
              null,
              null,
              'Standard Parcel Electric\n11:00pm \u2022 12:30 hrs',
              null,
              'x',
              null,
            ],
            ['Total Rostered', null, 3, 12.0, 7, 'x', null],
            [],
            ['Elodie Ashdown', 'T007', null, 'Late row after total', null, 'x', null],
            ['Total Rostered again', null, 1, 5, null, 'x', null],
          ],
        },
      ],
      day: '2026-09-01',
    },
    {
      error:
        "This schedule doesn't cover Tuesday, September 01 2026.\n\nThe weeks it has are: Mon, 03/Aug, Tue, 04/Aug, Wed, 05/August, Fri, 07/Aug",
    },
  ],
  [
    {
      name: 'the first sheet is used when the named one is missing',
      importer: 'schedule',
      file: 'Week-32-Schedule.xlsx',
      sheets: [
        {
          name: 'Whatever',
          rows: [
            ['Rostered Work Blocks'],
            ['Week 32, 2026'],
            [],
            [
              'Associate Name',
              'Transporter ID',
              'Mon, 03/Aug',
              'Tue, 04/Aug',
              'Wed, 05/August',
              'Thu, 06/Foo',
              'Fri, 07/Aug',
            ],
            [
              'Carmen Abernathy',
              'T001',
              'Standard Parcel Step Van - US\n9:55am - 10 hrs',
              'Standard Parcel Step Van - US\n9:55am \u2022 10 hrs',
              null,
              'x',
              null,
            ],
            [
              'Nadine Abernathy',
              'T002',
              '9:50am - 10 hrs',
              '9:50 AM \u00b7 9 hrs \u00b7 break',
              'Service only',
              'x',
              null,
            ],
            [
              'Nolan Abernathy|Barrett Ainsworth',
              'T003|T004',
              null,
              'Electric\r\n10:05 AM | 8 hrs\nextra line',
              '  ',
              'x',
              null,
            ],
            ['Colton Alderman', 'T005', null, '\n', 'Standard Parcel\n\n10:25am', 'x', null],
            [null, 'T006', null, 'Ghost row', null, 'x', null],
            [
              'Zane Applewhite',
              null,
              null,
              'Standard Parcel Electric\n11:00pm \u2022 12:30 hrs',
              null,
              'x',
              null,
            ],
            ['Total Rostered', null, 3, 12.0, 7, 'x', null],
            [],
            ['Elodie Ashdown', 'T007', null, 'Late row after total', null, 'x', null],
            ['Total Rostered again', null, 1, 5, null, 'x', null],
          ],
        },
        {
          name: 'Other',
          rows: [['x']],
        },
      ],
      day: '2026-08-04',
    },
    {
      kind: 'schedule',
      day: '2026-08-04',
      sourceTotal: 5,
      rows: [
        {
          transporterId: 'T001',
          driverName: 'Carmen Abernathy',
          routeCode: '',
          dispatchTime: '9:55am',
          serviceType: 'Standard Parcel Step Van - US',
          routeDuration: '',
          vin: '',
          detail: '10 hrs',
          sharedDrivers: 'Carmen Abernathy',
          sharedIds: 'T001',
          pad: '',
        },
        {
          transporterId: 'T002',
          driverName: 'Nadine Abernathy',
          routeCode: '',
          dispatchTime: '9:50am',
          serviceType: '',
          routeDuration: '',
          vin: '',
          detail: '9 hrs break',
          sharedDrivers: 'Nadine Abernathy',
          sharedIds: 'T002',
          pad: '',
        },
        {
          transporterId: 'T003',
          driverName: 'Nolan Abernathy',
          routeCode: '',
          dispatchTime: '10:05am',
          serviceType: 'Electric',
          routeDuration: '',
          vin: '',
          detail: '8 hrs',
          sharedDrivers: 'Nolan Abernathy|Barrett Ainsworth',
          sharedIds: 'T003|T004',
          pad: '',
        },
        {
          transporterId: '',
          driverName: 'Zane Applewhite',
          routeCode: '',
          dispatchTime: '11:00pm',
          serviceType: 'Standard Parcel Electric',
          routeDuration: '',
          vin: '',
          detail: '12:30 hrs',
          sharedDrivers: 'Zane Applewhite',
          sharedIds: '',
          pad: '',
        },
        {
          transporterId: 'T007',
          driverName: 'Elodie Ashdown',
          routeCode: '',
          dispatchTime: '',
          serviceType: 'Late row after total',
          routeDuration: '',
          vin: '',
          detail: '',
          sharedDrivers: 'Elodie Ashdown',
          sharedIds: 'T007',
          pad: '',
        },
      ],
    },
  ],
  [
    {
      name: 'no header row',
      importer: 'schedule',
      file: 'Week-32-Schedule.xlsx',
      sheets: [
        {
          name: 'Rostered Work Blocks',
          rows: [
            ['Name', 'Team'],
            ['Carmen Abernathy', 'Blue'],
          ],
        },
      ],
      day: '2026-08-04',
    },
    {
      error:
        "Couldn't find the header row.\n\nExpected a row containing 'Associate Name' and 'Transporter ID' - is this a weekly schedule export?",
    },
  ],
  [
    {
      name: 'no day columns',
      importer: 'schedule',
      file: 'Week-32-Schedule.xlsx',
      sheets: [
        {
          name: 'Rostered Work Blocks',
          rows: [
            ['Associate Name', 'Transporter ID', 'Notes'],
            ['Carmen Abernathy', 'T001', 'x'],
          ],
        },
      ],
      day: '2026-08-04',
    },
    {
      error: 'The schedule has no day columns.',
    },
  ],
  [
    {
      name: 'an empty sheet',
      importer: 'schedule',
      file: 'Week-32-Schedule.xlsx',
      sheets: [
        {
          name: 'Rostered Work Blocks',
          rows: [],
        },
      ],
      day: '2026-08-04',
    },
    {
      error: 'The sheet is empty.',
    },
  ],
  [
    {
      name: 'a headcount of zero rows',
      importer: 'schedule',
      file: 'Week-32-Schedule.xlsx',
      sheets: [
        {
          name: 'Rostered Work Blocks',
          rows: [
            ['Associate Name', 'Transporter ID', 'Tue, 04/Aug'],
            ['Total', null, 4],
          ],
        },
      ],
      day: '2026-08-04',
    },
    {
      error: 'Nobody is rostered on Tue, 04/Aug in this schedule.',
    },
  ],
];

describe('route export scenarios', () => {
  it.each(SCENARIOS.map(([scenario, expected]) => ({ scenario, expected })))(
    '$scenario.name',
    async ({ scenario, expected }) => {
      expect(await runScenario(scenario)).toEqual(expected);
    },
  );
});
